### ISSUE TITLE
Bootstrap Framwork Messed Up Current UI

### ISSUE THREAD

**Issue by kvb2univpitt** [kvb2univpitt/i2b2-saml-demo#3]
Bootstrap v5 framework is used for the new, redesigned login page.  However, it messed up the current Javascript UI layout.  Need to dive deep down into the Bootstrap framework to find out the what CSS code causes for the layout to mess up.

**Comment by kvb2univpitt** [comment]
It turns out that Bootstrap framework uses border-box for box-sizing.  Need to set box-sizing to content-box for the original UI to look proper.  Added the following CSS code to the index.php:

```css
*,
*::before,
*::after {
    box-sizing: content-box;
}

#i2b2_login_modal_dialog * {
    box-sizing: border-box;
}
```

The code above will set the box-sizing to content-box and set the box-sizing  of the redesigned login dialog to border-box.
